include:
  - path: ./supabase/docker-compose.yml
    env_file:
      - ./supabase/.env

services:
  frontend:
    build:
      context: .                       # корень проекта
      dockerfile: ./vite-project/Dockerfile
    ports:
      - "80:80"                        # доступ к SPA по http://localhost
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./vite-project/.env
      - ./supabase/.env
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=http://kong:8000
      - VK_ACCESS_TOKEN=${VK_ACCESS_TOKEN:-}
      - VK_VIDEO_OWNER_ID=${VK_VIDEO_OWNER_ID:--202211208}
      - VK_VIDEO_PLAYLIST_ID=${VK_VIDEO_PLAYLIST_ID:-8}

  python-backend:
    build:
      context: ./python-backend        # папка с Python backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
