version: '3.9'

services:
  frontend:
    build:
      context: .                       # корень проекта
      dockerfile: ./vite-project/Dockerfile
    ports:
      - "80:80"                        # доступ к SPA по http://localhost
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  python-backend:
    build:
      context: ./python-backend        # папка с Python backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"