# 🔹 Настройка кеша для внешнего API
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=NBA_CACHE:50m inactive=30m max_size=200m;

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 🔹 Прокси на Node backend внутри Docker Compose
    location /api/daily-games {
        proxy_pass http://backend:3000/api/daily-games;   # имя сервиса из docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 🔹 Прокси на внешний API с кешем
    location /api/external/ {
        proxy_cache NBA_CACHE;
        proxy_cache_valid 200 30m;              # кешируем успешные ответы 30 минут
        proxy_cache_use_stale error timeout updating;
        proxy_cache_key "$scheme$request_method$host$request_uri";
        add_header X-Cache-Status $upstream_cache_status;

        proxy_pass https://api.balldontlie.io/v1/;  # обязательно слэш
        proxy_ssl_server_name on;

        # 🔹 API ключ добавляется к каждому запросу
        include /etc/nginx/headers.conf;
        proxy_set_header Host api.balldontlie.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 🔹 SPA fallback
    location / {
        try_files $uri /index.html;
    }

    location /api/standings/ {
        proxy_pass http://backend:3000/api/standings/;
    }

    location /api/player-stats/ {
        proxy_pass http://backend:3000/api/player-stats/;
    }

    location /api/player-gamelog/ {
            proxy_pass http://backend:3000/api/player-gamelog/;
    }

    location /api/team-games/ {
                proxy_pass http://backend:3000/api/team-games/;
    }

    location /api/team-upcoming-games/ {
                    proxy_pass http://backend:3000/api/team-upcoming-games/;
    }

    location /api/game-detail/ {
        proxy_pass http://backend:3000/api/game-detail/;
    }

    location /api/game-recap/ {
        proxy_pass http://backend:3000/api/game-recap/;
    }

    location /api/games/by-date/ {
        proxy_pass http://backend:3000/api/games/by-date/;
    }

    location /api/player-image/ {
        proxy_pass http://backend:3000/api/player-image/;

        proxy_cache NBA_CACHE;
        proxy_cache_valid 200 30d;
        proxy_cache_use_stale error timeout updating;

        proxy_cache_key "$scheme$request_method$host$request_uri";

        add_header X-Cache-Status $upstream_cache_status;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}