export const teamsFullNames: Record<string, string> = {
    DAL: 'Dallas Mavericks',
    MIL: 'Milwaukee Bucks',
    PHX: 'Phoenix Suns',
    ORL: 'Orlando Magic',
    CHA: 'Charlotte Hornets',
    BKN: 'Brooklyn Nets',
    TOR: 'Toronto Raptors',
    DET: 'Detroit Pistons',
    NYK: 'New York Knicks',
    HOU: 'Houston Rockets',
    CLE: 'Cleveland Cavaliers',
    LAL: 'Los Angeles Lakers',
    POR: 'Portland Trail Blazers',
    LAC: 'Los Angeles Clippers',
    MEM: 'Memphis Grizzlies',
    PHI: 'Philadelphia 76ers',
    WAS: 'Washington Wizards',
    BOS: 'Boston Celtics',
    MIA: 'Miami Heat',
    ATL: 'Atlanta Hawks',
    SAC: 'Sacramento Kings',
    IND: 'Indiana Pacers',
    CHI: 'Chicago Bulls',
    DEN: 'Denver Nuggets',
    UTA: 'Utah Jazz',
    SAS: 'San Antonio Spurs',
    GSW: 'Golden State Warriors',
    OKC: 'Oklahoma City Thunder',
    MIN: 'Minnesota Timberwolves',
    NOP: 'New Orleans Pelicans'
}