create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  first_name text not null default '',
  last_name text not null default '',
  avatar_img text,
  hide_scores boolean not null default true,
  admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.map_points (
  id bigint generated by default as identity primary key,
  logo text not null,
  x numeric not null,
  y numeric not null,
  link text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_comments (
  id uuid primary key default gen_random_uuid(),
  game_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null default '',
  image_data text,
  created_at timestamptz not null default now(),
  constraint game_comments_has_content check (
    length(trim(message)) > 0 or image_data is not null
  )
);

create index if not exists game_comments_game_id_created_at_idx
on public.game_comments (game_id, created_at);

create table if not exists public.game_comment_reads (
  game_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (game_id, user_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists map_points_set_updated_at on public.map_points;
create trigger map_points_set_updated_at
before update on public.map_points
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.map_points enable row level security;
alter table public.game_comments enable row level security;
alter table public.game_comment_reads enable row level security;

drop policy if exists "Profiles are visible to their owners" on public.profiles;
create policy "Profiles are visible to their owners"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Map points are public" on public.map_points;
create policy "Map points are public"
on public.map_points for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert map points" on public.map_points;
create policy "Admins can insert map points"
on public.map_points for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can update map points" on public.map_points;
create policy "Admins can update map points"
on public.map_points for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can delete map points" on public.map_points;
create policy "Admins can delete map points"
on public.map_points for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Authenticated users can read game comments" on public.game_comments;
create policy "Authenticated users can read game comments"
on public.game_comments for select
to authenticated
using (true);

drop policy if exists "Users can insert their own game comments" on public.game_comments;
create policy "Users can insert their own game comments"
on public.game_comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read their game comment reads" on public.game_comment_reads;
create policy "Users can read their game comment reads"
on public.game_comment_reads for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their game comment reads" on public.game_comment_reads;
create policy "Users can insert their game comment reads"
on public.game_comment_reads for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their game comment reads" on public.game_comment_reads;
create policy "Users can update their game comment reads"
on public.game_comment_reads for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.profiles;
    alter publication supabase_realtime add table public.game_comments;
  end if;
exception
  when duplicate_object then null;
end;
$$;

insert into public.map_points (id, logo, x, y, link)
values
  (7, '/logos/GSW.svg', 13.1508397466152, 42.6957007801298, '/team/GSW'),
  (10, '/logos/LAL.svg', 16.5804333333676, 54.0205132539138, '/team/LAL'),
  (11, '/logos/SAC.svg', 15.7295850066934, 41.4958946868426, '/team/SAC'),
  (18, '/logos/PHX.svg', 20.9839357429719, 59.0842776684536, '/team/PHX'),
  (20, '/logos/DEN.svg', 31.8607764390897, 36.7188030128249, '/team/DEN'),
  (21, '/logos/OKC.svg', 39.1402395476897, 57.7729658983609, '/team/OKC'),
  (22, '/logos/DAL.svg', 39.8259705488621, 66.1775350026012, '/team/DAL'),
  (23, '/logos/HOU.svg', 40.5622489959839, 73.9945941055393, '/team/HOU'),
  (25, '/logos/SAS.svg', 35.6749352170052, 76.6913559788302, 'team/SAS'),
  (27, '/logos/NOP.svg', 46.285140562249, 73.7050733980231, '/team/NOP'),
  (29, '/logos/MEM.svg', 47.0883534136546, 54.8138472325892, '/team/MEM'),
  (30, '/logos/ATL.svg', 53.4805890227577, 57.130012892719, '/team/ATL'),
  (32, '/logos/CHA.svg', 55.5555555555556, 51.0500780348782, '/team/CHA'),
  (33, '/logos/MIA.svg', 59.3373493975904, 82.4630748003891, '/team/MIA'),
  (34, '/logos/ORL.svg', 57.1285140562249, 73.560313044265, '/team/ORL'),
  (35, '/logos/WAS.svg', 61.1780455153949, 37.5873651353736, '/team/WAS'),
  (36, '/logos/PHI.svg', 62.6840696117805, 30.2045870937097, '/team/PHI'),
  (37, '/logos/NYK.svg', 60.809906291834, 18.9132795005768, '/team/NYC'),
  (39, '/logos/BOS.svg', 65.4712251506078, 22.9533959489674, '/team/BOS'),
  (40, '/logos/TOR.svg', 55.8902275769746, 24.1246522358689, '/team/TOR'),
  (42, '/logos/CLE.svg', 53.9156626506024, 32.7378932844767, '/team/CLE'),
  (50, '/logos/DET.svg', 51.6398929049531, 31.2179095700165, '/team/DET'),
  (51, '/logos/IND.svg', 50.6358768406961, 39.7587704417453, '/team/IND'),
  (53, '/logos/CHI.svg', 46.6867469879518, 32.4483725769605, '/team/CHI'),
  (54, '/logos/MIL.svg', 47.5681459132703, 27.5563097019085, '/team/MIL'),
  (55, '/logos/MIN.svg', 41.5327978580991, 22.8218090520459, '/team/MIN'),
  (56, '/logos/BKN.svg', 60.3779643289057, 27.3335363080365, '/team/BKN'),
  (58, '/logos/LAC.svg', 14.2904953145917, 51.4119789192735, '/team/LAC'),
  (13, '/logos/POR.svg', 14.0562248995984, 14.4257085340752, '/team/POR'),
  (14, '/logos/UTA.svg', 25.6358768406961, 34.6197778833322, '/team/UTA')
on conflict (id) do update
set
  logo = excluded.logo,
  x = excluded.x,
  y = excluded.y,
  link = excluded.link;

select setval(
  pg_get_serial_sequence('public.map_points', 'id'),
  coalesce((select max(id) from public.map_points), 1)
);
