create extension if not exists pgcrypto;
create extension if not exists pg_cron;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  first_name text not null default '',
  last_name text not null default '',
  avatar_img text,
  hide_scores boolean not null default true,
  favorites_teams text[] not null default '{}',
  favorites_players jsonb not null default '[]'::jsonb,
  favorites_games jsonb not null default '[]'::jsonb,
  watched_games jsonb not null default '[]'::jsonb,
  following_profiles text[] not null default '{}',
  notify_followed_comments boolean not null default false,
  notifications jsonb not null default '[]'::jsonb,
  admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists favorites_teams text[] not null default '{}';

alter table public.profiles
add column if not exists favorites_players jsonb not null default '[]'::jsonb;

alter table public.profiles
add column if not exists favorites_games jsonb not null default '[]'::jsonb;

alter table public.profiles
add column if not exists watched_games jsonb not null default '[]'::jsonb;

alter table public.profiles
add column if not exists following_profiles text[] not null default '{}';

alter table public.profiles
add column if not exists notify_followed_comments boolean not null default false;

alter table public.profiles
add column if not exists notifications jsonb not null default '[]'::jsonb;

create table if not exists public.map_points (
  id bigint generated by default as identity primary key,
  logo text not null,
  x numeric not null,
  y numeric not null,
  link text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_progress_rules (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in ('watched_games', 'top_team')),
  max_games integer not null check (max_games > 0),
  title text not null default '',
  description text not null default '',
  svg text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category, max_games)
);

create table if not exists public.game_comments (
  id uuid primary key default gen_random_uuid(),
  game_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null default '',
  image_data text,
  reply_to_id uuid references public.game_comments(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint game_comments_has_content check (
    length(trim(message)) > 0 or image_data is not null
  )
);

alter table public.game_comments
add column if not exists reply_to_id uuid references public.game_comments(id) on delete set null;

create index if not exists game_comments_game_id_created_at_idx
on public.game_comments (game_id, created_at);

create index if not exists game_comments_reply_to_id_idx
on public.game_comments (reply_to_id);

create table if not exists public.game_comment_reads (
  game_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (game_id, user_id)
);

create table if not exists public.nba_games_by_date_cache (
  date_key date primary key,
  payload jsonb not null default '[]'::jsonb,
  game_count integer not null default 0,
  source text not null default 'python-backend',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nba_games_by_date_cache_payload_is_array check (jsonb_typeof(payload) = 'array'),
  constraint nba_games_by_date_cache_game_count_non_negative check (game_count >= 0)
);

create index if not exists nba_games_by_date_cache_fetched_at_idx
on public.nba_games_by_date_cache (fetched_at);

create table if not exists public.news_articles (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default '',
  slug text not null unique,
  excerpt text not null default '',
  content_html text not null default '',
  cover_image_url text,
  game_ids text[] not null default '{}',
  team_abbrs text[] not null default '{}',
  hashtags text[] not null default '{}',
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint news_articles_title_not_empty check (length(trim(title)) > 0),
  constraint news_articles_content_not_empty check (length(trim(content_html)) > 0)
);

create index if not exists news_articles_created_at_idx
on public.news_articles (created_at desc);

create index if not exists news_articles_game_ids_idx
on public.news_articles using gin (game_ids);

create index if not exists news_articles_team_abbrs_idx
on public.news_articles using gin (team_abbrs);

create index if not exists news_articles_hashtags_idx
on public.news_articles using gin (hashtags);

alter table public.news_articles
add column if not exists team_abbrs text[] not null default '{}';

create table if not exists public.news_slider_items (
  id uuid primary key default gen_random_uuid(),
  image_url text not null,
  link_url text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint news_slider_items_image_not_empty check (length(trim(image_url)) > 0)
);

create index if not exists news_slider_items_created_at_idx
on public.news_slider_items (created_at desc);

create table if not exists public.news_article_comments (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.news_articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null default '',
  image_data text,
  reply_to_id uuid references public.news_article_comments(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint news_article_comments_has_content check (
    length(trim(message)) > 0 or image_data is not null
  )
);

create index if not exists news_article_comments_article_id_created_at_idx
on public.news_article_comments (article_id, created_at);

create index if not exists news_article_comments_reply_to_id_idx
on public.news_article_comments (reply_to_id);

create table if not exists public.news_article_comment_reads (
  article_id uuid not null references public.news_articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (article_id, user_id)
);

create table if not exists public.news_article_likes (
  article_id uuid not null references public.news_articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id, user_id)
);

create index if not exists news_article_likes_user_created_at_idx
on public.news_article_likes (user_id, created_at desc);

create table if not exists public.profile_news_notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  article_id uuid not null references public.news_articles(id) on delete cascade,
  comment_id uuid references public.news_article_comments(id) on delete cascade,
  kind text not null default 'article_published' check (kind in ('article_published', 'article_comment')),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint profile_news_notifications_recipient_article_kind_key unique (recipient_id, article_id, kind),
  constraint profile_news_notifications_recipient_comment_kind_key unique (recipient_id, comment_id, kind)
);

alter table public.profile_news_notifications
add column if not exists comment_id uuid references public.news_article_comments(id) on delete cascade;

alter table public.profile_news_notifications
drop constraint if exists profile_news_notifications_kind_check;

alter table public.profile_news_notifications
add constraint profile_news_notifications_kind_check
check (kind in ('article_published', 'article_comment'));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profile_news_notifications_recipient_comment_kind_key'
      and conrelid = 'public.profile_news_notifications'::regclass
  ) then
    alter table public.profile_news_notifications
    add constraint profile_news_notifications_recipient_comment_kind_key
    unique (recipient_id, comment_id, kind);
  end if;
end $$;

create index if not exists profile_news_notifications_recipient_created_at_idx
on public.profile_news_notifications (recipient_id, created_at desc);

create or replace function public.cleanup_old_game_comment_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.game_comment_reads
  where read_at < now() - interval '4 days';

  delete from public.game_comments
  where created_at < now() - interval '4 days';
end;
$$;

revoke all on function public.cleanup_old_game_comment_data() from public;

select cron.unschedule(jobid)
from cron.job
where jobname = 'cleanup-old-game-comment-data';

select cron.schedule(
  'cleanup-old-game-comment-data',
  '0 * * * *',
  $$select public.cleanup_old_game_comment_data();$$
);

create table if not exists public.profile_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint profile_follows_no_self_follow check (follower_id <> following_id)
);

insert into public.profile_follows (follower_id, following_id)
select profiles.id, followed_id::uuid
from public.profiles
cross join lateral unnest(profiles.following_profiles) as followed_id
where followed_id <> ''
on conflict (follower_id, following_id) do nothing;

create table if not exists public.profile_comment_notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  game_id text not null,
  comment_id uuid not null references public.game_comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  unique (recipient_id, comment_id)
);

create index if not exists profile_comment_notifications_recipient_created_at_idx
on public.profile_comment_notifications (recipient_id, created_at desc);

create index if not exists profile_follows_following_id_idx
on public.profile_follows (following_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists map_points_set_updated_at on public.map_points;
create trigger map_points_set_updated_at
before update on public.map_points
for each row execute function public.set_updated_at();

drop trigger if exists profile_progress_rules_set_updated_at on public.profile_progress_rules;
create trigger profile_progress_rules_set_updated_at
before update on public.profile_progress_rules
for each row execute function public.set_updated_at();

drop trigger if exists nba_games_by_date_cache_set_updated_at on public.nba_games_by_date_cache;
create trigger nba_games_by_date_cache_set_updated_at
before update on public.nba_games_by_date_cache
for each row execute function public.set_updated_at();

drop trigger if exists news_articles_set_updated_at on public.news_articles;
create trigger news_articles_set_updated_at
before update on public.news_articles
for each row execute function public.set_updated_at();

drop trigger if exists news_slider_items_set_updated_at on public.news_slider_items;
create trigger news_slider_items_set_updated_at
before update on public.news_slider_items
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.map_points enable row level security;
alter table public.profile_progress_rules enable row level security;
alter table public.game_comments enable row level security;
alter table public.game_comment_reads enable row level security;
alter table public.nba_games_by_date_cache enable row level security;
alter table public.profile_follows enable row level security;
alter table public.profile_comment_notifications enable row level security;
alter table public.news_articles enable row level security;
alter table public.news_slider_items enable row level security;
alter table public.news_article_comments enable row level security;
alter table public.news_article_comment_reads enable row level security;
alter table public.news_article_likes enable row level security;
alter table public.profile_news_notifications enable row level security;

drop policy if exists "Profiles are visible to their owners" on public.profiles;
create policy "Profiles are visible to their owners"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Map points are public" on public.map_points;
create policy "Map points are public"
on public.map_points for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert map points" on public.map_points;
create policy "Admins can insert map points"
on public.map_points for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can update map points" on public.map_points;
create policy "Admins can update map points"
on public.map_points for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can delete map points" on public.map_points;
create policy "Admins can delete map points"
on public.map_points for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Profile progress rules are public" on public.profile_progress_rules;
create policy "Profile progress rules are public"
on public.profile_progress_rules for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert profile progress rules" on public.profile_progress_rules;
create policy "Admins can insert profile progress rules"
on public.profile_progress_rules for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can update profile progress rules" on public.profile_progress_rules;
create policy "Admins can update profile progress rules"
on public.profile_progress_rules for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can delete profile progress rules" on public.profile_progress_rules;
create policy "Admins can delete profile progress rules"
on public.profile_progress_rules for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Authenticated users can read game comments" on public.game_comments;
create policy "Authenticated users can read game comments"
on public.game_comments for select
to authenticated
using (true);

drop policy if exists "Users can insert their own game comments" on public.game_comments;
create policy "Users can insert their own game comments"
on public.game_comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users and admins can delete game comments" on public.game_comments;
create policy "Users and admins can delete game comments"
on public.game_comments for delete
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Users can read their game comment reads" on public.game_comment_reads;
create policy "Users can read their game comment reads"
on public.game_comment_reads for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their game comment reads" on public.game_comment_reads;
create policy "Users can insert their game comment reads"
on public.game_comment_reads for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their game comment reads" on public.game_comment_reads;
create policy "Users can update their game comment reads"
on public.game_comment_reads for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read their profile follows" on public.profile_follows;
create policy "Users can read their profile follows"
on public.profile_follows for select
to authenticated
using (auth.uid() = follower_id);

drop policy if exists "Users can follow profiles" on public.profile_follows;
create policy "Users can follow profiles"
on public.profile_follows for insert
to authenticated
with check (auth.uid() = follower_id);

drop policy if exists "Users can unfollow profiles" on public.profile_follows;
create policy "Users can unfollow profiles"
on public.profile_follows for delete
to authenticated
using (auth.uid() = follower_id);

drop policy if exists "Users can read their profile comment notifications" on public.profile_comment_notifications;
create policy "Users can read their profile comment notifications"
on public.profile_comment_notifications for select
to authenticated
using (auth.uid() = recipient_id);

drop policy if exists "Users can update their profile comment notifications" on public.profile_comment_notifications;
create policy "Users can update their profile comment notifications"
on public.profile_comment_notifications for update
to authenticated
using (auth.uid() = recipient_id)
with check (auth.uid() = recipient_id);

drop policy if exists "Users can delete their profile comment notifications" on public.profile_comment_notifications;
create policy "Users can delete their profile comment notifications"
on public.profile_comment_notifications for delete
to authenticated
using (auth.uid() = recipient_id);

drop policy if exists "NBA games cache is public" on public.nba_games_by_date_cache;
create policy "NBA games cache is public"
on public.nba_games_by_date_cache for select
to anon, authenticated
using (true);

drop policy if exists "Published news articles are public" on public.news_articles;
create policy "Published news articles are public"
on public.news_articles for select
to anon, authenticated
using (
  published = true
  or exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can insert news articles" on public.news_articles;
create policy "Admins can insert news articles"
on public.news_articles for insert
to authenticated
with check (
  auth.uid() = author_id
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can update news articles" on public.news_articles;
create policy "Admins can update news articles"
on public.news_articles for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can delete news articles" on public.news_articles;
create policy "Admins can delete news articles"
on public.news_articles for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "News slider items are visible" on public.news_slider_items;
create policy "News slider items are visible"
on public.news_slider_items for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert news slider items" on public.news_slider_items;
create policy "Admins can insert news slider items"
on public.news_slider_items for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Admins can delete news slider items" on public.news_slider_items;
create policy "Admins can delete news slider items"
on public.news_slider_items for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Authenticated users can read news article comments" on public.news_article_comments;
create policy "Authenticated users can read news article comments"
on public.news_article_comments for select
to authenticated
using (true);

drop policy if exists "Users can insert their own news article comments" on public.news_article_comments;
create policy "Users can insert their own news article comments"
on public.news_article_comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users and admins can delete news article comments" on public.news_article_comments;
create policy "Users and admins can delete news article comments"
on public.news_article_comments for delete
to authenticated
using (
  auth.uid() = user_id
  or exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.admin = true
  )
);

drop policy if exists "Users can read their news article comment reads" on public.news_article_comment_reads;
create policy "Users can read their news article comment reads"
on public.news_article_comment_reads for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their news article comment reads" on public.news_article_comment_reads;
create policy "Users can insert their news article comment reads"
on public.news_article_comment_reads for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their news article comment reads" on public.news_article_comment_reads;
create policy "Users can update their news article comment reads"
on public.news_article_comment_reads for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "News article likes are visible" on public.news_article_likes;
create policy "News article likes are visible"
on public.news_article_likes for select
to anon, authenticated
using (true);

drop policy if exists "Users can like news articles" on public.news_article_likes;
create policy "Users can like news articles"
on public.news_article_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unlike news articles" on public.news_article_likes;
create policy "Users can unlike news articles"
on public.news_article_likes for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read their news notifications" on public.profile_news_notifications;
create policy "Users can read their news notifications"
on public.profile_news_notifications for select
to authenticated
using (auth.uid() = recipient_id);

drop policy if exists "Users can update their news notifications" on public.profile_news_notifications;
create policy "Users can update their news notifications"
on public.profile_news_notifications for update
to authenticated
using (auth.uid() = recipient_id)
with check (auth.uid() = recipient_id);

drop policy if exists "Users can delete their news notifications" on public.profile_news_notifications;
create policy "Users can delete their news notifications"
on public.profile_news_notifications for delete
to authenticated
using (auth.uid() = recipient_id);

drop trigger if exists game_comments_create_profile_notifications on public.game_comments;
drop function if exists public.create_profile_comment_notifications();

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.profiles;
    alter publication supabase_realtime add table public.game_comments;
    alter publication supabase_realtime add table public.profile_follows;
    alter publication supabase_realtime add table public.profile_comment_notifications;
    alter publication supabase_realtime add table public.news_articles;
    alter publication supabase_realtime add table public.news_article_comments;
    alter publication supabase_realtime add table public.news_article_likes;
    alter publication supabase_realtime add table public.profile_news_notifications;
    alter publication supabase_realtime add table public.news_slider_items;
  end if;
exception
  when duplicate_object then null;
end;
$$;

insert into public.map_points (id, logo, x, y, link)
values
  (7, '/logos/GSW.svg', 13.1508397466152, 42.6957007801298, '/team/GSW'),
  (10, '/logos/LAL.svg', 16.5804333333676, 54.0205132539138, '/team/LAL'),
  (11, '/logos/SAC.svg', 15.7295850066934, 41.4958946868426, '/team/SAC'),
  (18, '/logos/PHX.svg', 20.9839357429719, 59.0842776684536, '/team/PHX'),
  (20, '/logos/DEN.svg', 31.8607764390897, 36.7188030128249, '/team/DEN'),
  (21, '/logos/OKC.svg', 39.1402395476897, 57.7729658983609, '/team/OKC'),
  (22, '/logos/DAL.svg', 39.8259705488621, 66.1775350026012, '/team/DAL'),
  (23, '/logos/HOU.svg', 40.5622489959839, 73.9945941055393, '/team/HOU'),
  (25, '/logos/SAS.svg', 35.6749352170052, 76.6913559788302, 'team/SAS'),
  (27, '/logos/NOP.svg', 46.285140562249, 73.7050733980231, '/team/NOP'),
  (29, '/logos/MEM.svg', 47.0883534136546, 54.8138472325892, '/team/MEM'),
  (30, '/logos/ATL.svg', 53.4805890227577, 57.130012892719, '/team/ATL'),
  (32, '/logos/CHA.svg', 55.5555555555556, 51.0500780348782, '/team/CHA'),
  (33, '/logos/MIA.svg', 59.3373493975904, 82.4630748003891, '/team/MIA'),
  (34, '/logos/ORL.svg', 57.1285140562249, 73.560313044265, '/team/ORL'),
  (35, '/logos/WAS.svg', 61.1780455153949, 37.5873651353736, '/team/WAS'),
  (36, '/logos/PHI.svg', 62.6840696117805, 30.2045870937097, '/team/PHI'),
  (37, '/logos/NYK.svg', 60.809906291834, 18.9132795005768, '/team/NYC'),
  (39, '/logos/BOS.svg', 65.4712251506078, 22.9533959489674, '/team/BOS'),
  (40, '/logos/TOR.svg', 55.8902275769746, 24.1246522358689, '/team/TOR'),
  (42, '/logos/CLE.svg', 53.9156626506024, 32.7378932844767, '/team/CLE'),
  (50, '/logos/DET.svg', 51.6398929049531, 31.2179095700165, '/team/DET'),
  (51, '/logos/IND.svg', 50.6358768406961, 39.7587704417453, '/team/IND'),
  (53, '/logos/CHI.svg', 46.6867469879518, 32.4483725769605, '/team/CHI'),
  (54, '/logos/MIL.svg', 47.5681459132703, 27.5563097019085, '/team/MIL'),
  (55, '/logos/MIN.svg', 41.5327978580991, 22.8218090520459, '/team/MIN'),
  (56, '/logos/BKN.svg', 60.3779643289057, 27.3335363080365, '/team/BKN'),
  (58, '/logos/LAC.svg', 14.2904953145917, 51.4119789192735, '/team/LAC'),
  (13, '/logos/POR.svg', 14.0562248995984, 14.4257085340752, '/team/POR'),
  (14, '/logos/UTA.svg', 25.6358768406961, 34.6197778833322, '/team/UTA')
on conflict (id) do update
set
  logo = excluded.logo,
  x = excluded.x,
  y = excluded.y,
  link = excluded.link;

select setval(
  pg_get_serial_sequence('public.map_points', 'id'),
  coalesce((select max(id) from public.map_points), 1)
);
